services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # REST API / Web UI
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true   # можно оставить, но начиная с 2.12/3.x demo-setup всё равно требует пароль
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyStr0ngP@ssw0rd123!
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" # REST API (BM25)
      - "9600:9600"
    volumes:
      - ./opensearch_data:/usr/share/opensearch/data

  cassandra:
    image: cassandra:latest
    container_name: cassandradb
    restart: unless-stopped
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=Test Cluster


volumes:
  cassandra-data:
    external: true
    name: 906de87ffa13bdb8780ffb9d371cfbc5970814d12b40ef05aac0c53a21b72248
